// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4_a2VRSlxpdqRyImbRvDyIfIcBvSqNU',
    appId: '1:692569406849:web:1e4e4a53d8b056dd69bc80',
    messagingSenderId: '692569406849',
    projectId: 'newproject-dd2ba',
    authDomain: 'newproject-dd2ba.firebaseapp.com',
    storageBucket: 'newproject-dd2ba.appspot.com',
    measurementId: 'G-40P0N3JJY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA62_SJoD05XUNFsxc5mXMrOlZK0qc_UBY',
    appId: '1:692569406849:android:6260e1ed7048bd5a69bc80',
    messagingSenderId: '692569406849',
    projectId: 'newproject-dd2ba',
    storageBucket: 'newproject-dd2ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG8Y9tqAH1Lr2r8yGHoYaZsjgPge6yuFY',
    appId: '1:692569406849:ios:b1e0f6029ccda71b69bc80',
    messagingSenderId: '692569406849',
    projectId: 'newproject-dd2ba',
    storageBucket: 'newproject-dd2ba.appspot.com',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG8Y9tqAH1Lr2r8yGHoYaZsjgPge6yuFY',
    appId: '1:692569406849:ios:30d77be6d67efc1769bc80',
    messagingSenderId: '692569406849',
    projectId: 'newproject-dd2ba',
    storageBucket: 'newproject-dd2ba.appspot.com',
    iosBundleId: 'com.example.firstProject.RunnerTests',
  );
}
